### PR TITLE
PEP8.sh: Add E101 and E113

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by jbleyel** [comment]
Are you sure? Automatically repair intention can break the code logic.

**Comment by persianpros** [comment]
We're using it, example: https://github.com/OpenVisionE2/enigma2-plugins/commit/6291c5fce297d46748d687f5a2c7a52ceec03597

It only fixes parts of the code when things got mixed.

**Comment by jbleyel** [comment]
E113 is OK
E101 is not OK

**Comment by jbleyel** [comment]
> We're using it, example: [OpenVisionE2/e2iplayer-ov@5038b26](https://github.com/OpenVisionE2/e2iplayer-ov/commit/5038b26789083d94104b368fb8ad520cd528c480)
> 
> It only fixes parts of the code when things got mixed.
> 
> The result will be cleaner files to look and work on, we may need to fix something by hand later but chances for that is like 1 file in 30 files which is acceptable.
> 
> Those files are the fucked up files with mixed indentation so better find and fix them instead of ignoring them.

You may have a different version of autopep8 ..
The autopep8 will change ALL tabs to space If I use E101 on my machine.
I have version 1.6

**Comment by persianpros** [comment]
@jbleyel 

You may want to add https://github.com/OpenVisionE2/TurquoiseHD-skin/commit/34dbe110c2de0a140dd5770422a8ea619f5e39c4 to Metrix and other ATV skins, result: https://github.com/OpenVisionE2/TurquoiseHD-skin/commit/7603b3db0ec40f2450f9ca0fe2b95548142c855c

**Comment by persianpros** [comment]
@jbleyel 

You may want to add https://github.com/OpenVisionE2/TurquoiseHD-skin/commit/34dbe110c2de0a140dd5770422a8ea619f5e39c4 to Metrix and other ATV skins, result: https://github.com/OpenVisionE2/TurquoiseHD-skin/commit/7603b3db0ec40f2450f9ca0fe2b95548142c855c

Also https://github.com/OpenVisionE2/enigma2-openvision/commit/512d2a208bf5e109b62b5a3ce32ef3b9b74ea54b which does https://github.com/OpenVisionE2/enigma2-openvision/commit/415035d02ae3214af4a9d169683e398590ec906d

**Comment by jbleyel** [comment]
Not Bad.. Thanks

**Pull request closed without merging**
