### PR TITLE
Add enhanced signal finder

### PR DESCRIPTION
**Pull request by wedebe**
This change introduces a new (beta) signal finder page, subtly
accessible from the right-side header button, beside the (new)
fullscreen toggle button.

Not part of this change:
- replacement of existing sigfinder
- option to change ping frequency
- option to turn off sound
- inaccessible/disconnected receiver indication
- websocket usage rather than hammering ajax requests
- proper mobile responsiveness
- i10n
- code to be proud of
- guaranteed torture-free dish setup

Screen Shot 2020-10-10 at 12 05 25
Screen Shot 2020-10-10 at 12 16 54

### CODE REVIEW

**Comment by wedebe** [comment]
Can anyone tell me what BER measures? It always seems to be returned as `0` from the api, but the bar is forced to fill status.

**Comment by IanSav** [comment]
BER represents the Bit Error Rate.  It is a rating of the quality of the signal.  Zero is normal and means a good clean signal.

[BER Information Link 1](https://www.etsi.org/deliver/etsi_etr/200_299/290/01_60/etr_290e01p.pdf)
[BER Information Link 2](https://www.researchgate.net/publication/320856039_CNR_and_BER_ranges_for_the_DVB-T2_reception-success)

**Comment by betacentauri** [comment]
BER = Bit error rate. 
In normal case it should be always 0. If you have bad reception you should see higher values. But it also depends on the drivers which don’t always deliver reasonably values.

**Comment by jbleyel** [comment]
You can also check this.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/909

**Comment by wedebe** [comment]
Thanks all! I'll check for BER when I get my DVB-T tuner and aerial all hooked up.

**Pull request merged**
