### PR TITLE
Revert "[servicelist.py] Bug fix in reloadServicesLists()"

### PR DESCRIPTION
**Pull request by Huevos**
This reverts https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/2629beca15b8322222e8b08d2babce2380e1bfc3

This has been fixed in enigma cpp code so the above mentioned commit is no longer necessary.

Fixed in OpenViX ( https://github.com/OpenViX/enigma2/commit/cc0703417c8c37d564b0544d9a41a8a778e5bb44 )
Fixed in OpenPLi ( https://github.com/OpenPLi/enigma2/commit/c018baadcf74d0cce382f485447be39469ebc2cc )
Fixed in OpenATV ( https://github.com/openatv/enigma2/commit/c22a20d045512c0546fbc62ce3cca64ddc25307f )
Fixed in OpenMIPS ( https://github.com/openmips/stbgui/commit/347d5208dd142836a4d6be69877f8c521ce0934b )

### CODE REVIEW

**Comment by Schimmelreiter** [comment]
I'll leave it in for a bit longer, there are more distros to consider here:
Black Hole, OpenBlackHole, OpenDroid, OpenNFR, OpenSPA, VTi, ...

**Comment by Huevos** [comment]
You were reluctant to accept this workaround saying it should be fixed in enigma2 cpp code. And now this is fixed in enigma2 you are reluctant to revert the workaround.

Should we really be bloating code because some teams are too lazy to merge bug fixes into their code even when they have been handed to them on a plate?

**Comment by Schimmelreiter** [comment]
No, just give them some time.

**Comment by Schimmelreiter** [comment]
Two weeks should be enough for everybody.

**Comment by Huevos** [comment]
Two years not enough for some. ;)

**Comment by Schimmelreiter** [comment]
First you complain that I did not merge instantly and now because I waited "only" two weeks ;)

**Pull request merged**
