### PR TITLE
Feature channel tmpl improvements

### PR DESCRIPTION
**Pull request by doubleO8**
* code cleanup
* Added service tags indicating the kind of service (TV|HDTV|RADIO|UNKNOWN) and its namespace (DVB-C|DVB-S|UNKNOWN)

'original' theme:
screenshot_2017-10-24_20-15-55

'original-small-screen' theme:
screenshot_2017-10-24_20-16-58_original-small-screen

### CODE REVIEW

**Comment by jbleyel** [comment]
Hi @doubleO8, i don't like these service tags and namespaces furthermore i never need this.
Cause of SAT only, Radio Only and HD only bouquets.
Do you have test this with alternative services? I don't think so. ;-)

**Comment by doubleO8** [comment]
> i don't like these service tags and namespaces furthermore i never need this.
> Cause of SAT only, Radio Only and HD only bouquets.

Maybe there are others with **really messy** bouquets who would like to see these indicators :)

> Do you have test this with alternative services? I don't think so. ;-)

Actually I tested it with "alternative services" which yielded (TV,HDTV,RADIO,UNKNOWN) × (DVB-S, DVB-C). As I have cable and satellite access this was the expected outcome.

**Comment by jbleyel** [comment]
Are you sure about mixing radio and tv. -> i'm not.
The namespace detection looks ok but you have forgot DVB-T.

The Service Type detection is not 100% correct.
If you check a full lamedb from a box with a rotor you will find this:
HD channels with SREF 1:0:1:... 
SD channels with SREF 1:0:16:...

**Comment by jbleyel** [comment]
Please check this.

[lamedb.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/1412243/lamedb.zip)

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/sourcefiles/js/bqe.js#L794

SREF  1:0:X:
1  = SD
2 = Radio
16 = SD4
19 = HD
1F = UHD
D3 = OPT

**Pull request merged**
