### PR TITLE
fix remote control dm8000

### PR DESCRIPTION
**Pull request by Dima73**
-not checked eTPM

### CODE REVIEW

**Comment by Schimmelreiter** [comment]
Not sure if we want to merge this:
Pretty much any box claims to be a dm8000 in proc.

This is not a problem if we catch the correct model elsewhere (Like we do for Vu+,...) but it would be an issue for any box where we don't.

As this fix is basically PLi-only it might affect Maxdigital and Formuler boxes (As well as ANY newly added box!):
PLi would still ship dmm1.png for such boxes without own remote but OWIF would miss-detect them to be using the dmm2 remote ....

Why is "orgdream" 0 on a real dm8000 anyways?

**Comment by Dima73** [comment]
Pli image not class eTPM

**Comment by Dima73** [comment]
openpli 4 formuler1


formuler1 login: root
root@formuler1:~# cat /proc/stb/info/model
dm800se
root@formuler1:~#

**Comment by Dima73** [comment]
Same output(dm800se) for et box.Not dm8000

**Comment by Schimmelreiter** [comment]
Solo²:
root@solo2 ~ # cat /proc/stb/info/model
dm8000
Duo²:
root@duo2 ~ # cat /proc/stb/info/model
dm8000
... and various others too.

Even if all boxes for which OpenPLi **currently** gets build
- output something different
or
- get properly detected otherwise
we would likely break some "Based on OpenPLi" images or at least introduce a ticking time bomb.

Checking for dm800se or dm8000 is never enough.

**Pull request closed without merging**
