### PR TITLE
Move public/themes/absb to /public/modern

### PR DESCRIPTION
**Pull request by wedebe**
This change also applies to /sourcefiles and
moves node modules into /modern.

Responsive .tmpl file paths updated

### CODE REVIEW

**Comment by jbleyel** [comment]
Do we need this file.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/sourcefiles/modern/yarn.lock

Please check also this: 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/network/alert/sourcefiles/modern/package-lock.json/yargs-parser/open

**Comment by wedebe** [comment]
> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/network/alert/sourcefiles/modern/package-lock.json/yargs-parser/open

Hi Jörg, yarn.lock is auto-generated and some sources say should be committed.
I've since come across this which leads me to believe package-lock.json should be committed instead, based on the use of npm.

https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files/44904494#44904494


I can't access the alert link.

**Comment by jbleyel** [comment]
Bildschirmfoto 2020-11-14 um 23 09 16

**Comment by jbleyel** [comment]
Bildschirmfoto 2020-11-14 um 23 11 09

**Pull request merged**
