### PR TITLE
VTi has no Screens.MovieSelection.moveServiceFiles

### PR DESCRIPTION
**Pull request by rdamas**

### CODE REVIEW

**Comment by jbleyel** [comment]
But how about the function?
Do VTi have no config.usage.movielist_trashcan?

**Comment by jbleyel** [comment]
How about?
```

			if '.Trash' not in fullpath and config.usage.movielist_trashcan.value:
				result = False
				message = "trashcan"
				try:
					import Tools.Trashcan
					trash = Tools.Trashcan.createTrashFolder(srcpath)
					if trash:
						try:
							from Screens.MovieSelection import moveServiceFiles
							moveServiceFiles(service.ref, trash)
							result = True
							message = "The recording '%s' has been successfully moved to trashcan" % name
						except ImportError:
							# Fallback
							res = _moveMovie(session, sRef, destpath=trash)
							result = res['result']
							message = res['message']
							pass
				except ImportError:
					message = "trashcan exception"
					pass
				except Exception as e:
					message = "Failed to move to .Trash folder: %s" + str(e)
					print(message)
				deleted = True

```

**Comment by RobvanderDoes** [comment]
Hard to satisfy a 'closed source' image (:

**Comment by jbleyel** [comment]
Hello @RobvanderDoes ,
VTi will use this repository again for the IPK of the VTi feed. Just like it was about 2 years ago. 
So everything will be back the way it was.

**Pull request merged**
