### PR TITLE
Optimise stb & remote imagery

### PR DESCRIPTION
**Pull request by wedebe**
Optimise box images

This change:
- saves **~3MB** of space
- converts png files to jpg
- crops out excess padding
- applies PNGOUT, OxiPNG and AdvPNG, JPEGOptim and Jpegtran optimisations and strips metadata via ImageOptim
- sets a max width of 1000px to a small number of images

### CODE REVIEW

**Comment by jbleyel** [comment]
Not good.
The image needs to be transparent.
And you will not save space because you do not have all images on your box.

**Comment by jbleyel** [comment]
Just for information.
We plan to remove all images from OWI and get them from here 
https://github.com/oe-alliance/remotes
in future.

**Comment by jbleyel** [comment]
The branding module will also removed in future.

**Comment by wedebe** [comment]
> Just for information. We plan to remove all images from OWI and get them from here https://github.com/oe-alliance/remotes in future.

Shouldn't the stb photos be centralised to `oe-alliance` too?

**Comment by jbleyel** [comment]
This is the plan.
BUT OWI is also for other images out of oe-a.

That's why I plan a version 2 for OE-A and the old 1.X version will be code freeze.
I also plan a new Repro for this.
This takes some time and some more preparations.

**Comment by wedebe** [comment]
> And you will not save space because you do not have all images on your box.

I'm not sure what you mean by this, could you clarify, please?

**Comment by jbleyel** [comment]
The feed ipk contains only your box and not all.

**Comment by wedebe** [comment]
> The feed ipk contains only your box and not all.

Ah I see. I've done a set of optimised PNGs in transparent background format, I'll open a fresh PR.

**Pull request merged**
