### PR TITLE
Fixes EPG times

### PR DESCRIPTION
**Pull request by diogosena**
This was showing wrong times when not on UTC timezone

### CODE REVIEW

**Comment by Schimmelreiter** [comment]
XML TV is supposed to deliver times in UTC, thus it also delivers the offset.

**Comment by diogosena** [comment]
> XML TV is supposed to deliver times in UTC, thus it also delivers the offset.
Tvheadend and Kodi disagree, doesn't make sense to send the offset if you are sending utc time, offset for utc is always zero.
Just try any program that support xmltv, and you'll see.

**Comment by Schimmelreiter** [comment]
I do use this Interface, resp. TV-Browser does.

**Comment by diogosena** [comment]
What's your timezone offset? did you tried any other programs? in my case, it's -3:00, without this fix epg is completely messed up in every program. I tried android iptv, kodi iptv simple client, emby, jellyfin, perfect player and many others.
All of them need this fix to work correctly, doesn't seem likely that every other iptv program using xmltv is wrong.

**Pull request closed without merging**
