### PR TITLE
fix original dm8000 remote control

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by Schimmelreiter** [comment]
Won't solve the problem either:
You added the **known** conditions for boxes that claim to be dm8000 but aren't, but I was speaking about boxes that are yet to come.
For **known** boxes, procmodel = dm8000 already won't come up as a result, because it gets taken care of before.

I'll make an alternative suggestion:
It would be much easier if PLi just replaces dmm.png and its map with the dmm2.png and its map during build when building for the DM8000.

The easiest way would be a proper boxbranding however, as mentioned a zillion times already.
A proper boxbranding could even also handle different images for identical boxes under different brand names, even with different remotes.

**Comment by Dima73** [comment]
At the moment, it solves the problem.
Why not just apply the patch and all.

**Comment by Schimmelreiter** [comment]
Because OpenPLi is not the center of the world.
Other teams use this repo as well and build for other machines than OpenPLi does and not necessarily all of those machines get properly detected.
So there might be - and probably are - teams that rely on the fallback remote to properly work.

**Comment by Dima73** [comment]
I do not understand ...
It's just 100% working solution.
And in no way touches the other images.
I just want to help users dm8000.
Let's apply this patch and wait for test users.

**Comment by Dima73** [comment]
Schimmelreiter
Please apply this patch.
He's really a good solution, in my opinion.

**Comment by Schimmelreiter** [comment]
I've already told you why it is not, objective, not opinion.

**Comment by jbleyel** [comment]
IMHO ... I don't understand this discussion.
If this patch is only openPLi related then you are wrong here in this repository.
This is the master of openwebif and this repository is for all images without any image related patches.
You can add any feature but no image related fixes.

**Comment by Dima73** [comment]
not only openPLi  
all image

**Comment by Schimmelreiter** [comment]
@jbleyel The "fix" is not really OpenPLi specific but it only works for the limited set of boxes supported by it **now**.
So for now it would probably work for OpenPLi, but it will definitely not work for other teams that build for other boxes that can not be properly detected in owibranding.
Such boxes rely on the OWIF falling back to the standard dream remote but with the "fix" any new box would randomly fall back to the standard **or** the DM8000 remote.

That means it will as well likely fail on new boxes OpenPLi starts to build for.

Mathematically:
Instead of a unique and reliable detection of the DM8000 box on its own, it relies on excluding a limited subset of other known boxes and assuming DM8000 after exclusion of this limited subset.

Simple representation:
if a <> 1 {
 print "A is 2"
}

This would still print "A is 2" even if a = 3.

You simply can not just say "A is 2" for all cases where A is not 1 and if Dima73 still doesn't get this now, I can't help anymore.

**Comment by littlesat** [comment]
What should be a proper fix for this then?

**Comment by Schimmelreiter** [comment]
1. Properly detect the DM8000 by really detecting DM8000; NOT by excluding the limited known amount of boxes claiming to be DM8000 that can be detected not to be one (Avoid new such boxes being detected as DM8000 also) ... (Probably not possible, at least not easily in Python).
2. Simply replace the default dmm remote (files) with the DM8000 remote (files) during build for the DM8000 (Needs to be done in the PLi git/DM8000 build)
3. Actually kind of 1+2: Use a boxbranding like in oe-a.
4. Getting rid of box specific full remotes entirely and instead using a generic one optimized for web use

**Comment by RobvanderDoes** [comment]
ad 4: Please, please do!

**Comment by Dima73** [comment]
I do not understand, it's that simple:
-	elif procmodel == "dm8000" and orgdream:
+	elif procmodel == "dm8000" and (orgdream or not fileExists("/proc/stb/info/vumodel") and not fileExists("/proc/stb/info/boxtype")):
 		remote = "dmm1"

And the issue closed.

**Comment by milosoftware** [comment]
The openwebif package is already MACHINE specific. It's already known compile-time which box it's going to be installed on, so why not simply use that reliable information?

**Comment by Schimmelreiter** [comment]
@milosoftware:
That's exactly what I'm telling all the time.

Instead of guessing that "if its not a Vu+ it COULD be a DM8000", just replace the dmm style default remote with the dmm1 style one for DM8000 while building for DM8000 (Option 2 from my list above).
And as far as the remote design is concerned, it's about the same as including a proper oe-a style boxbranding into the image (as in option 3).

**Pull request closed without merging**
