### PR TITLE
Fix blue screen when you stream via RemoteStreamConvert

### PR DESCRIPTION
**Pull request by javilonas**
This corrects the BSOD that occurs in the host server from a client to zap receiver using the plugin RemoteStreamConvert

### CODE REVIEW

**Comment by RobvanderDoes** [comment]
Can you please explain: how/when/why did the crash occur?

**Comment by Schimmelreiter** [comment]
try ... except can never harm ;-)

**Comment by RobvanderDoes** [comment]
Well, actually it does:
1- try/except just hides a bug, instead of exposing it so the cause can be fixed, and
2- it makes the code bulky, slower, and harder to read.

**Comment by plnick** [comment]
Fully agree with Rob.

This code is in use for years, so it can not be a common issue. Hiding the issue with try / except is not a solution here, the root cause of the described problem should be found by detailed failure description

MERGE was reverted

**Comment by Schimmelreiter** [comment]
As a matter of fact, an external app/client can obviously form a request in a way that makes OpenWebif crash.
So no matter if the client **should** form the request differently, the problem inside OWIF remains.

**Pull request merged**
