### PR TITLE
add option custom location , e.g. as timer name

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by Dima73** [comment]
<The timer will not start if the location is not in recording locations.>
RecordTimer.py-->def findSafeRecordPath:
	if not os.path.isdir(dirname):
		try:
			os.makedirs(dirname)
		except Exception, ex:
			print '[RecordTimer] Failed to create dir "%s":' % dirname, ex


<Do you have a modified autotimer plugin?>
Yes,please see this:
https://sourceforge.net/p/openpli/plugins-enigma2/ci/e76dec4ed452b055b5a46d70315a171bb49cabae/
and this:
https://sourceforge.net/p/openpli/enigma2/ci/0eb39a5fb3c9e6fe60b167b64f5b5c012c7ae33a/

discussion this:
http://forums.openpli.org/topic/38048-bug-on-autotimer-edit-via-openwebif/

I tested the patch, everything works fine.

**Comment by Schimmelreiter** [comment]
Yes, Dima73 uses some autotimer mod: The variant from OpenPLi.

That's why I haven't merged this yet, it needs testing with the normal autotimer plugin first.

**Comment by Dima73** [comment]
This patch will not break the standard/normal version autotimer plugin.

P.S.Instead, you must add this same patch editing standard timers for openwebif.

**Comment by Schimmelreiter** [comment]
I'll give it a test ride ...

**Comment by Schimmelreiter** [comment]
I created a new autotimer which worked fine. That autotimer also created timers w/o problems.

There is also no functional change at all, but I'll blame that to the lack of that "custom location" in my autotimer plugin.
The relevance of the test was just to see if it works with the regular autotimer and it does.

**Pull request merged**
