### PR TITLE
[info.py] picon path order

### PR DESCRIPTION
**Pull request by AbuBaniaz**
Flash memory is faster, so check those locations first.

### CODE REVIEW

**Comment by rdamas** [comment]
Please don't merge - yes flash memory is faster, but file system caching should absolutely compensate for this. 

I have one reason case for not changing the currently used search order: 
I use a bright Enigma2 skin and therefore a darker set of picons, and I love the standard blue background of OpenWebif, but the darker set of picons don't look good with it (in fact sometimes are hardly "readable"). 

So I use the existing search order to use a different set of picons for OpenWebif than for Enigma2 GUI. If /usr/share/enigma2/picon comes first, I'm stuck to the default set, which is not acceptable for me.

**Comment by jbleyel** [comment]
We should add the picon source folder for openwebif as setting to use different picons for web and OSD.

**Comment by rdamas** [comment]
Yes, that sounds like the way to go.

**Comment by jbleyel** [comment]
I will try it.

**Comment by Schimmelreiter** [comment]
Flash **must** come last to allow the usual overrides.

**Pull request closed without merging**
