### PR TITLE
Update for json content type

### PR DESCRIPTION
**Pull request by fbradyirl**
@jbleyel @Schimmelreiter This is the proper fix for json content types on the server.

I have tested this and it works well for me.

Apologies about the first PR!

### CODE REVIEW

**Comment by jbleyel** [comment]
this is not all but you have fixed a very old small bug

**Comment by fbradyirl** [comment]
@jbleyel Haha. I'm not sure what you mean, but I am happy to help out!

**Comment by jbleyel** [comment]
This is only for json and utf-8 is missing.
This will not work for all browsers.
setHeader did not work sometimes.

**Comment by fbradyirl** [comment]
@jbleyel You need me to add `; charset=utf-8` to the header? I can do that yes if it is needed?

**Comment by jbleyel** [comment]
Stop!!!

**Comment by jbleyel** [comment]
Please collect all needed changes first and made the hole commit.
Don't commit all single changes.

**Comment by fbradyirl** [comment]
Sure, I will do it in one commit. I am just trying to ascertain what is required.

**Pull request merged**
