### PR TITLE
[owibranding.py] update SF8008

### PR DESCRIPTION
**Pull request by Huevos**

### CODE REVIEW

**Comment by WanWizard** [comment]
@Huevos , you have to be very careful with this kind of changes. First your broke box images for all VU+ boxes, this commit has broken the box image for the sf8008.

**Comment by ims21** [comment]
this is cooperation, as Mr Huevos wants it ...

**Comment by WanWizard** [comment]
This is broken for all images, not only OpenPLi. Lets keep things civilized please.

I doubt it is intentional, more likely not aware of the side effects.

**Comment by ims21** [comment]
Ok, everyone has the right to be naive...

**Pull request merged**
