### PR TITLE
Use correct type for param eventid in eEPGCache.lookupEventId

### PR DESCRIPTION
**Pull request by rdamas**

### CODE REVIEW

**Comment by jbleyel** [comment]
I thinks this is not needed.
See here.
```
		eit = 0
		if "eventid" in request.args.keys():
			eventid = request.args["eventid"][0]
		elif "eit" in request.args.keys() and type(request.args["eit"][0]) is int:
			eventid = request.args["eit"][0]
		else:
			from enigma import eEPGCache, eServiceReference
			queryTime = int(request.args["begin"][0]) + (int(request.args["end"][0]) - int(request.args["begin"][0])) / 2
			event = eEPGCache.getInstance().lookupEventTime(eServiceReference(request.args["sRef"][0]), queryTime)
			eventid = event and event.getEventId()
		if eventid is not None:
			eit = int(eventid)

```

**Comment by jbleyel** [comment]
We should move this : 

```
			from enigma import eEPGCache, eServiceReference
			queryTime = int(request.args["begin"][0]) + (int(request.args["end"][0]) - int(request.args["begin"][0])) / 2
			event = eEPGCache.getInstance().lookupEventTime(eServiceReference(request.args["sRef"][0]), queryTime)
			eventid = event and event.getEventId()
```

to the timers.py

**Comment by rdamas** [comment]
I don't see how this will help: the block you mention uses parameters "begin" and "end".

I had a fail when adding an event with sRef and eventid as parameters (coming from P_timeraddbyeventid), where eventid was transferred as string to addTimerByEventId(). 

The first blocks already successfully casts parameter "eventid" to int (eit), which then isn't used when calling addTimerByEventId().

**Comment by jbleyel** [comment]
i will fix this

**Pull request closed without merging**
