### PR TITLE
Issue 986: Remote control in mobile view

### PR DESCRIPTION
**Pull request by rdamas**
Adds a link to the remote view cloned from desktop presentation.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
@rdamas Which image and receivers did you try this on please?

I am getting "error loading page".  I have tried on PLi and OpenVix and OpenATV using GB UE 4K. Also TM Nano SE M2 using OpenViX.

**Comment by jbleyel** [comment]
Hi @rdamas , i think someone with high html skill should build a html only version without image.

**Comment by rdamas** [comment]
Agreed, this is a quick'n'dirty solution; we had this discussion some years ago already, and I would love to see a SVG solution. But that's definitely not my terrain ;-)

**Comment by jbleyel** [comment]
https://freesvg.org/remote-control-symbol

**Comment by jbleyel** [comment]
See here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/503

**Pull request merged**
