### PR TITLE
too long text on a button

### PR DESCRIPTION
**Pull request by s3n0**
Compress text on a button. Unfortunately, the size of the button does not allow you to insert too long text.

It may be appropriate to adjust the style of the buttons - to increase their width.
https://www.imgup.cz/images/2018/01/20/image0001.png

### CODE REVIEW

**Comment by jbleyel** [comment]
Please test your 2 pulls first. You should put your corresponding changes in one single pull.

**Comment by s3n0** [comment]
My last change could fix my previous mistakes (as I have described in the comments):

1. To translate too long text into two lines in the button:

- This is a mistake in web-design styles
- the width of the text and the size of the buttons should be adapted to the length of the text and not the other way - when I use 25 characters in the text instead of 13 characters, will not I see all the buttons? uhm, good crap
- at least automatic font size adjustment could have been, if the text is in two rows (in a button) ... but I'm not a web-designer, so I can not do that

2. Window height correction that appears when changing power mode:
- I wanted to edit the translation text for my native language, but it was unsuccessful
- if I knew it was such a PROBLEM to add one word in addition to a translation, I would not even try it

I really do not have free time and nerves, so I leave it the way it is. Sorry. I'm an old system programmer, a developer in Assembler. I'm not an experienced Python programmer or a web-designer.

Um, test the code? Too much time for someone who does not deal with Python programming. So, unfortunately it remains the way it is. Of course I tried it a few days ago - unsuccessfully. In a set top box, I would need to install another "brothel" just to compile the python python source code (.py) into an even more compressed python (.pyo). OpenATV I use is not enough to just reboot to compile the .py to .pyo

GitHub is designed badly, but do not talk about it here :-).

I'm new to the GitHub server. I have no idea how to combine 2 or more pull-requests. I do not want to study an hour of gigantic instructions for use. GitHub reminds me of the Windows10 or Android graphical interface - it's a huge color graphical icon that you click when it clicks, so everything is done automatically by itself (unfortunately never the way the user wants it).

I will leave the OpenWebif code to someone who would take 10 minutes instead of 10 hours in my case. I do not plan to engage in Python programming or web-design ever in my life.

Sorry. Good luck.

P.S.
Adding two additional modes to power control needs a lot of people to know. It often happens that the set top box boots in standby but with the TV screen off. Or, it is often the case that OpenWebif sees that the satellite tuner is active even though the power switch graphic is red - the set top box is off (red switch) - in which case "Toggle Standby" is inapplicable - other the words mish-mah. And then it is better to click on "standby" or "wake up" - depending on what the user needs to do.

**Comment by jbleyel** [comment]
only some short hints:

* The translation should be understandable and if the text is too long we can change the UI to fit the text.

* to test your code on your box you need some python and enigma2 skill

* github is only the host and not for editing. You better use a local git repository of your fork, you only need to make a single commit with all changes and then push to your online fork. And then make the pull.

* The 2 new buttons are not needed. You can get the current state first and then change the text of the 1. button. This needs some more code.

**Comment by s3n0** [comment]
Hello.

So ... I tested it.

I installed the ipk package from OpenWebif GitHub (opkg install - force-reinstall ..... ipk). Python source code (.py) was also installed. However, the source code is inapplicable because there are some components missing in the OpenATV image for compiling python code, and I do not want to worry about it for another hour. Only with the start of the Python compiler I would be worried again for at least 2 hours. I searched for Google, nothing helped, so I left it after one hour of attempts.

Finally, I adjusted the numeric value of the window height through HexEditor (really like a jerk) and tested it. I have also changed the data in the template as well as in the source code. Although the template is about informative only, and the python source code (as I already wrote) in my box does not matter. The value for window height is:
425px
image0002

I also tested the translation into the Slovak language (using HexEditor and ending the text with byte "00h") and the name of the button in abbreviated form was finally pushed into the button. Previously, an incorrect translation of "Toggle Standby" was used - the same as the translation of the term "Standby". That's right:

Standby = Pohotovostný režim
Toggle Standby = Prepnúť pohotovostný režim

.... or a more comprehensible translation is this :
Toggle Standby = Prepnúť z/do pohotovostného režimu          (Switch from/to standby)
Toggle Standby = Prepnúť z/do pohotov. režimu                      (short-cut)

I know only the elementary basis of Python programming language and I'm not an expert. There is no problem in the python code to change one number and test it. However, the problem is the same in all other modern languages ​​- Java, PHP, Perl, ASP, Flash, JavaScript, Python, ... - There is a problem with compiling and debugging the source code, always on a different platform - firmware, other hardware. Paradoxically, the fact that these programming languages ​​were designed just to allow the source code to be transmitted and run on another platform. But, paradoxically, that is why most problems arise.

The other 2 power control modes really need a lot of people (service technicians). It often happens that the Linux box will run in "half-stop" mode when the OpenWebif power switch is red and when the tuner is active. Then, when you click on "Toggle Standby", the TV screen and the set top box are unfortunately switched on. If someone is asleep at night, the noise from the TV will wake him up. It's just chaos. Adding two more power management modes eliminates this chaos! The "standby" switch is generally stupid. The "standby" switch function is used on common home devices. In the case of Linux boxing, it's quite a problem if the service technician sets, modifies, adjusts the configuration. One small note: OpenWebif does not serve to ordinary but experienced users. They certainly appreciate another two options for "enter standby" and "leave standby", instead of the switching into Cosmos :) .

**Pull request closed without merging**
