### PR TITLE
list all properly loaded external web plugins under addons section 

### PR DESCRIPTION
**Pull request by j00zek**

### CODE REVIEW

**Comment by jbleyel** [comment]
What's happen if plugins[3] is not defined?

**Comment by j00zek** [comment]
The registration entry point for external webchild is pluginshook.src, which accepts only those with 4 arguments. So, plugins[3] has to be defined. or external addon won't be registered by openwebif.

Please also note appending is within try.

**Comment by jbleyel** [comment]
Do you have test the fancontrol plugin?
I think this will no longer work after your change.
You need to prevent duplicates.  e.g. epgrefresh, autotimer

The correct way should be a change of line 309 and add only tested plugins, in my mind.

**Comment by j00zek** [comment]
Fancontrol works properly with my change.
In fact it is universal and works for all new external web addons without a need to modify the code of openwebif each time.
I know how it can be frustrating when for unknown reason plugin you're working on does not work. I spent hours to find where the issue is.

Anyway, I will modify the code to just include my addon, if you prefer to keep the list of serviced external webparts closed.

**Pull request closed without merging**
