### PR TITLE
Add support for series picon

### PR DESCRIPTION
**Pull request by pr2git**
by dropping the ending Sxx Exx when searching for picon

### CODE REVIEW

**Comment by jbleyel** [comment]
Are you sure? This change affects only IPTV Channels.

**Comment by pr2git** [comment]
This change is not specific for IPTV but it is a last ressort test. So if any channel (whatever its type) has a picon available it will be displayed, if the channel has no picon then it will fall in the test for series. I didn't see any problem with this approach, since series is a last resort test. I have test it right now and with your last changes this is working really fine now.

**Comment by jbleyel** [comment]
Do you have a bouquet with a list of IPTV channels and each channel maps to a single episode of a series? And the channel name is ...SxxExx...

**Comment by pr2git** [comment]
Yes here is a screenshot of the final result:
capture d ecran 2018-08-28 a 21 32 25

**Pull request merged**
