### PR TITLE
Feature sass support

### PR DESCRIPTION
**Pull request by doubleO8**
* Use Sass for CSS handling
    
Quoting [http://sass-lang.com/documentation/file.SASS_REFERENCE.html](http://sass-lang.com/documentation/file.SASS_REFERENCE.html)
"_Sass is an extension of CSS that adds power and elegance to the
basic language. It allows you to use variables, nested rules,
mixins, inline imports, and more, all with a fully CSS-compatible syntax._"

Use Sass (SCSS) for generating, concatenating and minimising CSS contents.
Included is a script (`contrib/inotify_watcher.py`) which may be used to
ease development: It will monitor changes to `sourcesfiles/scss`.
If a change is detected the CSS files in `plugin/public/css` will be
generated+minimised (Using `contrib/inotify_watcher.py --force-update` one may force CSS content (re)generation).

* CSS includes cleanup (style.min.css will be generated by style.scss)
* Cheetah template cleanup and minor optimisation for page loading speed
* Fix: duplicated HTML element ID `leftmenu_*`
* Add new theme for small screens based on theme 'original': original-small-screen

### CODE REVIEW

**Comment by jbleyel** [comment]
How do i make the css on mac and windows?

**Comment by doubleO8** [comment]
mac and windows do not have inotify support thus the "automatic build on directory changes" provided by `contrib/inotify_watcher.py` will not work (or needs to implemented differently).
But if you installed Sass (see http://sass-lang.com/install) and the `scss` binary/script is in your `PATH` calling `contrib/inotify_watcher.py --force-update` should work.
Alternatively you may define environment variable `SCSS` in order to point to the location of the scss binary/script.

Base command is

	scss -t compressed --unix-newlines --sourcemap=none "in.scss":"out.css"

Some IDEs (e.g. [pycharm](https://www.jetbrains.com/pycharm/)) also provide Sass support.

**Comment by jbleyel** [comment]
/bin/sh: inotifywait: command not found

**Comment by jbleyel** [comment]
contrib/inotify_watcher.py --force-update 
WORKS

**Comment by doubleO8** [comment]
On linux you need to have installed a package providing `inotifywait` and a version that actually supports inotify :) 
For debian based distributions this would be `inotify-tools`.

**Pull request merged**
