### PR TITLE
Delete png meta data for libpng >=1.6.x iCCP chunk warning

### PR DESCRIPTION
**Pull request by persianpros**
Optipng is doing a great job for optimizing png files but it seems libpng >=1.6.x cares about iCCP chunk so we could easily remove all meta data from all png files for future warnings.
Also we would have smaller png files after this.

### CODE REVIEW

**Comment by Huevos** [comment]
Please don't merge this rubbish. People spend a lot of time getting images right only to have them damaged by having them run through an automated process.

**Comment by persianpros** [comment]
Just check PLi's git and even Open WebIF itself, We did this for all png files, All png files are optimized and I just saved your time for what's left, Anyway ...

**Comment by jbleyel** [comment]
You can make a new pull but only for the box images.
Then you ca make a second pull with the box remote control images.

All other images should be untouched.

**Comment by Huevos** [comment]
Again please don't merge this. Last time lots of files across OE-Alliance where damaged and it took forever to correct the mess.  People spend a long time creating decent images. They don't want people "optimizing" them.

**Comment by ims21** [comment]
"Just check PLi's git and even Open WebIF itself, We did this for all png files, All png files are optimized and I just saved your time for what's left, Anyway ..."

Yes, I had to fix then it :-(

**Pull request closed without merging**
