### PR TITLE
Feature improve theme customisability

### PR DESCRIPTION
**Pull request by doubleO8**
* add theme specific class(es) to body tag in order to ease CSS customisations

### CODE REVIEW

**Comment by jbleyel** [comment]
There is something wrong with one of your last commits.
The Header is wrong. / Chrome

bildschirmfoto 2017-10-15 um 10 08 35

**Comment by jbleyel** [comment]
Please look : #header h2

**Comment by jbleyel** [comment]
I have removed width: 500px; from #header h2 and it looks good.
But this is not the root cause for the destroyed header.
I don't like the current css for the header, but if you modify anything of the header you need to change the hole page. -> You don't want do this , Trust me.

**Comment by doubleO8** [comment]
#684 should fix the layout glitch (but clearly the error is that _Quelloffenes Webinterface für Linux-Receiver_ is way too long for the header ;)

> you need to change the whole page. -> You don't want do this , Trust me.

I've seen even worse HTML/CSS/JavaScript legacy crap than the stuff in OpenWebif – If code is not maintainable it will be adapted or abandoned.

**Comment by jbleyel** [comment]
The biggest problem is the right scrollarea and multiepg.
I have invest many hours to try a hole rebuild without success.

**Comment by doubleO8** [comment]
> The biggest problem is the right scrollarea and multiepg.
So maybe cramming the EPG layout in this small container is not the best layout choice.
I would move the EPG to a separate page with an entirely independent layout (e.g. like the EPG page of sky.de http://www.sky.de/tvguide-7599).

**Comment by jbleyel** [comment]
You can do it, but caution it's a lot of work.
And you should not change any api to prevent breaking 3rd party.

**Comment by doubleO8** [comment]
Merely a suggestion. The "EPG on enigma2 device" is another use case I don't see for me.
I use an internal web service for displaying of EPG data and request recordings using [enigma2_http_api](https://github.com/doubleO8/enigma2_http_api) thus I'm interested in a stable API too :)

**Pull request merged**
