### PR TITLE
Add "Search KinoPoisk" instead "Search IMDb" for the countries of the former CIS

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by ims21** [comment]
Would not be better for this languages make it selectable optionaly as "Imdb" OR "Kinopoisk" ?

**Comment by Dima73** [comment]
ims
This is the first step.
Then you can make a choice of languages with https://www.themoviedb.org/

**Comment by ims21** [comment]
you did not understand me... I thought optionaly choose, if user want "Imdb" or "Kinopoisk" (exist csfd too) ... not language...  it seems it is as censorship - for this languages will not be "Imdb", but "kinopoisk" only...

**Comment by eriksl** [comment]
Yes that is unacceptable.

**Pull request merged**
