### PR TITLE
fix: do not display channel labels when using themes other than origi…

### LINKED ISSUE #691: New labels only work in "original" theme
The labels for HD, UHD, SD4 and so on are only skinned in "original" theme, in other themes they look ugly:
image

### PR DESCRIPTION
**Pull request by doubleO8**
…nal-small-screen

fixes #691

### CODE REVIEW

**Comment by Schimmelreiter** [comment]
That will not fix separators getting interpreted though ...

**Comment by doubleO8** [comment]
Could you elaborate a bit on that please? I don't get which separators you are referring to and what issue(s) remain.

**Comment by Schimmelreiter** [comment]
See here:
image

There are tags behind "Schweiz", which is just a separator

**Comment by Schimmelreiter** [comment]
Or here, behind "Österreich" and using the original theme:
image

**Comment by Schimmelreiter** [comment]
And all stations on hotbird get tagged as "UNKNOWN" instead of DVB-S

**Comment by doubleO8** [comment]
I see. Thank you!
It seems you did not force reload (SHIFT-CTRL-R) the page after installing the altered CSS definitions.
After applying this patch no channel tag should be visible at all when using themes other than original-small-screen.

**Comment by jbleyel** [comment]
I have fixed the marker bug and i have defined DVB-S as default.
@doubleO8 : you should optimize the namespace check. Beginswith is the better way.
We have FFFFxxxx , EEEExxxx and other.
You don't want check other, trust me.

**Comment by Schimmelreiter** [comment]
And actually HD or SD4 should be DVB-S2 rather than DVB-S if I'm not entirely wrong.

**Pull request merged**
