### PR TITLE
Separate EPG, part 2 (Please test!)

### PR DESCRIPTION
**Pull request by wedebe**
This change:
- further improves EPG Cache calls

This change does not:
- (knowingly) change existing api/web/ajax response content

Known issues:
- fuzzy texts and custom date formats aren't finalised

### CODE REVIEW

**Comment by jbleyel** [comment]
Hi @wedebe
I took a closer look at the code for "epgEvent" and unfortunately had to realize that the new code is not good.
The conversion of the EPG data into the epgEvent class has a massive performance impact especially for multiepg.

**Comment by wedebe** [comment]
I plan to implement a tuple-output option for larger result sets, but in a manner in which functions external to the EPG class don't need to know the field indices involved.

BTW, the primary reason I previously implemented transformation through EPGCache's `convertFunc` was to avoid a doubled iteration (the data returned by EPGCache is looped through once again in order to build output).

I'd be keen to get some definitive before/after stats to work from and target, my Python benchmarking abilities are primitive at best!

**Comment by jbleyel** [comment]
I know your intention. I think you can only prevent the epgcache result loop if you implelemt the transform in epgcache c.

**Comment by wedebe** [comment]
> I know your intention. I think you can only prevent the epgcache result loop if you implelemt the transform in epgcache c.

Obviously a question for the EPGCache repo, but while we're on the topic - in your experience, how likely do you think it is that building object/json-formatted output could be implemented there?

**Comment by wedebe** [comment]
I also think we could further optimise queries by submitting sensible startTime/endTimes ranges to EPGCache.

`/web` (`/api`) and `/ajax` will be tidied up too, there's some ...stuff... that could be improved further.

**Comment by jbleyel** [comment]
I think we can optimize this in OWF 2.0

**Pull request merged**
