### PR TITLE
Migrate [modern js build] to Webpack from Parcel bundler

### LINKED ISSUE #1347: parcel-bundler V1 is deprecated
https://www.npmjs.com/package/parcel-bundler

### PR DESCRIPTION
**Pull request by wedebe**
Migrate to Webpack from Parcel bundler

Zero-config is inversely proportional to zero-headache 🙉

This change: 
- moves `modern` js file handling to webpack
- returns `modern` js building back to its own package.json for a cleaner separation of concerns
- changes from `require()` to `import` which is part of the JavaScript language spec
- closes #1347 ([Parcel] "V1 does everything we need it to!" may have been an untruth on my part 😬)

### CODE REVIEW

**Comment by wedebe** [comment]
Ready for review.

**Comment by jbleyel** [comment]
Hi @wedebe, looks good to me.
Do you have test the js changes?
Do you have test the github action?

**Comment by wedebe** [comment]
> Hi @wedebe, looks good to me.
> Do you have test the js changes?
> Do you have test the github action?

@jbleyel , all js and npm scripts fully tested; I haven't been able to test gh action locally, but the same `npm run build-js` command is utilised which in turn calls the modern build script.

**Comment by jbleyel** [comment]
I have done the merge.
Please check the github action.
I't looks like there is something wrong.

**Comment by jbleyel** [comment]
Please open this link
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/runs/3498163807?check_suite_focus=true
and check the build step "Build python 2.7".
This step includes the npm action.

**Comment by jbleyel** [comment]
This bot commit looks wrong.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/d0ca360bc59e165d5e2e56e140eaee7169b6aa4a

**Comment by wedebe** [comment]
> Please open this link
> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/runs/3498163807?check_suite_focus=true
> and check the build step "Build python 2.7".
> This step includes the npm action.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/runs/3498163807?check_suite_focus=true#step:7:2566

Files compiling as expected.

---

> This bot commit looks wrong.
> [d0ca360](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/d0ca360bc59e165d5e2e56e140eaee7169b6aa4a)

Diffing #d0ca360 with #813c6a6 shows multiple packages removed as the only change (babel, glob, etc and dependencies), #84ecdff can be ignored as it was a commit I made - similarly, the generated files were already generated by my local build which I'd committed, hence (I reckon) them not appearing in the build's commit log.

**Pull request merged**
