### PR TITLE
 Limit AutoTimer search types to AT plugin's available options 

### PR DESCRIPTION
**Pull request by wedebe**
Limit AutoTimer search types to AT plugin's available options (#1091) 

Use `typeMap` from `Plugins.Extensions.AutoTimer.AutoTimer`

### CODE REVIEW

**Comment by jbleyel** [comment]
Please respect ONLY the available types -> 

https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimer.py#L96
https://github.com/opendreambox/enigma2-plugins/blob/master/autotimer/src/AutoTimer.py#L98
https://github.com/openpli/enigma2-plugins/blob/master/autotimer/src/AutoTimer.py#L127
https://github.com/oe-alliance/enigma2-plugins/blob/master/vixautotimer/src/AutoTimer.py#L99

**Comment by wedebe** [comment]
> Please respect ONLY the available types ->
> 
> https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimer.py#L96
> https://github.com/opendreambox/enigma2-plugins/blob/master/autotimer/src/AutoTimer.py#L98
> https://github.com/openpli/enigma2-plugins/blob/master/autotimer/src/AutoTimer.py#L127
> https://github.com/oe-alliance/enigma2-plugins/blob/master/vixautotimer/src/AutoTimer.py#L99

Am I correct in thinking there'll _always_ be a `typeMap` available? If so, I'll remove the full hard-coded set.

**Comment by jbleyel** [comment]
There must be a typeMap.
I donno why i'm also add some extra options like 'full'.
It's too long ago.

Exact, partial and description should be always there.
start and end is optional.

OE,VIX :

typeMap = {
	"exact": eEPGCache.EXAKT_TITLE_SEARCH,
	"partial": eEPGCache.PARTIAL_TITLE_SEARCH,
	"start": eEPGCache.START_TITLE_SEARCH,
	"description": -99
}

DMM:
 
typeMap = {
	"exact": eEPGCache.EXAKT_TITLE_SEARCH,
	"partial": eEPGCache.PARTIAL_TITLE_SEARCH,
	"description": eEPGCache.PARTIAL_DESCRIPTION_SEARCH
}

PLI:
typeMap = {
	"exact": eEPGCache.EXAKT_TITLE_SEARCH,
	"partial": eEPGCache.PARTIAL_TITLE_SEARCH,
	"start": eEPGCache.START_TITLE_SEARCH,
	"end": eEPGCache.END_TITLE_SEARCH,
	"description": eEPGCache.PARTIAL_DESCRIPTION_SEARCH,
	"favoritedesc": -99
}

**Comment by wedebe** [comment]
Thanks @jbleyel , any idea what `favoritedesc` does?

**Comment by jbleyel** [comment]
favorites description match

**Comment by jbleyel** [comment]
https://github.com/OpenPLi/enigma2-plugins/blob/b1e3b630b1e2bb967a16f82dc3c0914996406d99/autotimer/src/AutoTimerEditor.py#L199

**Comment by wedebe** [comment]
@jbleyel So essentially a `bouquets == 'favourites' && searchType == 'description'` match?

**Comment by wedebe** [comment]
> Please respect ONLY the available types ->
> 
> https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimer.py#L96
> https://github.com/opendreambox/enigma2-plugins/blob/master/autotimer/src/AutoTimer.py#L98
> https://github.com/openpli/enigma2-plugins/blob/master/autotimer/src/AutoTimer.py#L127
> https://github.com/oe-alliance/enigma2-plugins/blob/master/vixautotimer/src/AutoTimer.py#L99

See change #1105 , is this ok?

**Comment by jbleyel** [comment]
Please use this:
https://github.com/OpenPLi/enigma2-plugins/blob/b1e3b630b1e2bb967a16f82dc3c0914996406d99/autotimer/src/AutoTimerEditor.py#L199

**Comment by wedebe** [comment]
@jbleyel how would I get these values into `ajax.py`? They don't seem to be exported in the AutoTimer code.

**Comment by jbleyel** [comment]
That's all what you need:

```
	#for $searchType in $searchTypes
		<option value="$searchType">$tstrings['at_'+$searchType+'_match']</option>
	#end for
```

All available searchTypes are:

typeMap = {
"exact": eEPGCache.EXAKT_TITLE_SEARCH,
"partial": eEPGCache.PARTIAL_TITLE_SEARCH,
"start": eEPGCache.START_TITLE_SEARCH,
"end": eEPGCache.END_TITLE_SEARCH,
"description": eEPGCache.PARTIAL_DESCRIPTION_SEARCH,
"favoritedesc": -99
}

The texts for the i8n strings are:
"partial" =  _("partial match")
"exact" =  _("exact match")
"start" =  _("title starts with")
"end" =  _("title ends with")
"description" =  _("description match")
"favoritedesc" =  _("favorites description match")

**Pull request merged**
