### PR TITLE
Use futurize to have python 3 compatible idioms

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by jbleyel** [comment]
Do you have test these changes on python2 and python3?

**Comment by persianpros** [comment]
We're using it on py2 only for now.

**Comment by jbleyel** [comment]
Maybe .. but the OWF is 100% py2 and py3 compatible and must be working on a py2 and py3 image.

**Comment by jbleyel** [comment]
Do you have a running py3 image?
Please contact me via mail.

**Pull request merged**
