### PR TITLE
Bugfix AutoTimer preview (#1351)

### PR DESCRIPTION
**Pull request by wedebe**
Bugfix AutoTimer preview (#1351)

This change:
- clears preview list between previews
- restores `Preview` button for Preview All functionality

### CODE REVIEW

**Comment by jbleyel** [comment]
Please use /simulate for previewAll. 

The autotimer /test function is optional.

**Comment by jbleyel** [comment]
Check this -> 

Test needs id:
https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimerResource.py#L90

No Test:
https://github.com/oe-alliance/enigma2-plugins/blob/master/vixautotimer/src/AutoTimerResource.py

The test request also has a different output and contains <e2state> tag.

**Comment by wedebe** [comment]
> Check this ->
> 
> Test:
> https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimerResource.py#L90
> 
> No Test:
> https://github.com/oe-alliance/enigma2-plugins/blob/master/vixautotimer/src/AutoTimerResource.py
> 
> The test request also has a different output and contains tag.
> 
> --
> 
> VTI and Dream has also a different autotimer.

Sorry, I know you've posted them before, @jbleyel ,but could you link to the other AutoTimer variants, please?

**Comment by jbleyel** [comment]
https://github.com/opendreambox/enigma2-plugins/blob/master/autotimer/src/AutoTimerResource.py

VTI is closed.

Maybe @rdamas can post the AutoTimerResource.py here.

**Comment by rdamas** [comment]
[AutoTimerResource.py.gz](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/6625486/AutoTimerResource.py.gz)

If I knew the repository from which the VTi version was branched, I'd have posted a link...

Can't find a matching version in the OE alliance plugins repo.

**Comment by jbleyel** [comment]
Thanks @rdamas .

Hi @wedebe,

**/test is only for single autotimer and /simulate is for all.**
 
as you can see here.

```
class AutoTimerTestResource(AutoTimerBackgroundingResource):
	def renderBackground(self, req):
		id = req.args.get("id")
		ret = []
		if id:
			autotimer = self.getAutoTimerInstance()
			ret = autotimer.parseEPG(simulateOnly = True, testtimer = str(id[0]))

		returnlist = ["<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<e2autotimertest api_version=\"", str(API_VERSION), "\">\n"]
		extend = returnlist.extend

		for (name, begin, end, serviceref, autotimername) in ret[3]:
			ref = ServiceReference(str(serviceref))
			extend((
				'<e2testtimer>\n'
				'   <e2servicereference>', stringToXML(serviceref), '</e2servicereference>\n',
				'   <e2servicename>', stringToXML(ref.getServiceName().replace('\xc2\x86', '').replace('\xc2\x87', '')), '</e2servicename>\n',
				'   <e2name>', stringToXML(name), '</e2name>\n',
				'   <e2timebegin>', str(begin), '</e2timebegin>\n',
				'   <e2timeend>', str(end), '</e2timeend>\n',
				'   <e2autotimername>', stringToXML(autotimername), '</e2autotimername>\n',
				'</e2testtimer>\n'
			))
		returnlist.append('</e2autotimertest>')
		req.setResponseCode(http.OK)
		req.setHeader('Content-type', 'application/xhtml+xml')
		req.setHeader('charset', 'UTF-8')
		return ''.join(returnlist)

```

**Pull request merged**
