### PR TITLE
[BoxInfo] Solve "TODO: get recording/timer info if more than one"

### PR DESCRIPTION
**Pull request by Huevos**
Correctly display info for multiple timers.

Each tuner shows corresponding recordings.

If any single tuner is recording multiple timers, all timers will show.

Tested: OpenViX Py3

### CODE REVIEW

**Comment by Huevos** [comment]
tuners

**Comment by Huevos** [comment]
@jbleyel can you merge this please

**Comment by jbleyel** [comment]
Let me test this on ATV first.

**Comment by Huevos** [comment]
Thanks.

**Pull request merged**
